version: '3'

services:
    nginx:
        image: nginx:1.20
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php
        container_name: soccer_nginx

    php:
        build: ./.docker/php
        restart: always

        working_dir: /var/www
        volumes:
            - ./:/var/www
            - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            PHP_IDE_CONFIG: "serverName=IDE"
        depends_on:
            - db
        container_name: soccer_app
        ports:
            - "8776:8080"

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: smart-soccer
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mariadb-data/:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: project_db

    phpmyadmin:
        image: phpmyadmin
        depends_on:
            - db
        environment:
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "8080:80"
        volumes:
            - ./pma-data:/var/lib/pma

volumes:
    mariadb-data:
    pma-data:
