version: '3'

services:
    nginx:
        image: nginx:1.20
        restart: always
        ports:
            - "80:80"
        volumes:
            - ./:/var/www/smart-soccer
            - ./.docker/nginx/conf.d:/etc/nginx/conf.d
        depends_on:
            - php
        container_name: soccer_nginx

    php:
        build: ./.docker/php
        restart: always
        volumes:
            - ./:/var/www/smart-soccer
            - ./.docker/php/conf.d/xdebug.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
        environment:
            PHP_IDE_CONFIG: "serverName=IDE"
        depends_on:
            - db
        container_name: soccer_app
        ports:
            - "8080:8080"

    db:
        image: mariadb
        restart: always
        environment:
            MYSQL_DATABASE: smart-soccer
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./mariadb-data/:/var/lib/mysql
        command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
        container_name: project_db
        ports:
            - "3306:3306"

volumes:
    mariadb-data:
    pma-data:
